//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaColumn
    {
        public MetaColumn()
        {
            this.CustomerDetails = new HashSet<CustomerDetail>();
        }
    
        public int ID { get; set; }
        public int MetaTableID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CustomerDetail> CustomerDetails { get; set; }
        public virtual MetaTable MetaTable { get; set; }
    }
}
